UNIVERSITY_DATAVERSE_MAP = {'acadia': 'acadia',
 'acadia university': 'acadia',
 'alberta': 'ualberta',
 'algoma': 'algoma',
 'algoma university': 'algoma',
 'athabasca': 'athabascau',
 'athabasca university': 'athabascau',
 "bishop's university": 'bishops',
 'bishops': 'bishops',
 'bishops university': 'bishops',
 'brandon': 'brandon',
 'brandon university': 'brandon',
 'british columbia': 'ubc',
 'brock': 'brock',
 'brock university': 'brock',
 'calgary': 'calgary',
 'cape breton': 'capebreton',
 'cape breton university': 'capebreton',
 'carleton': 'carleton',
 'carleton university': 'carleton',
 'cegep federation': 'federationcegeps',
 'concordia': 'concordia',
 'concordia university': 'concordia',
 'dal': 'dal',
 'dalhousie': 'dal',
 'dalhousie university': 'dal',
 'durham': 'durham',
 'durham college': 'durham',
 'ecole de technologie superieure': 'ets',
 "ecole nationale d'administration publique": 'enap',
 'enap': 'enap',
 'ets': 'ets',
 'fanshawe': 'fanshawe',
 'fanshawe college': 'fanshawe',
 'federation cegeps': 'federationcegeps',
 'georgian': 'georgian',
 'georgian college': 'georgian',
 'guelph': 'guelph',
 'hec': 'hec',
 'hec montreal': 'hec',
 'hec montréal': 'hec',
 'inrs': 'inrs',
 'institut national de la recherche scientifique': 'inrs',
 'lakehead': 'lakehead',
 'lakehead university': 'lakehead',
 'laurentian': 'laurentian',
 'laurentian university': 'laurentian',
 'laurier': 'laurier',
 'laval': 'laval',
 'lethbridge': 'lethbridge',
 'macewan': 'macewan',
 'macewan university': 'macewan',
 'manitoba': 'manitoba',
 'mcgill': 'mcgill',
 'mcgill university': 'mcgill',
 'mcmaster': 'mcmaster',
 'mcmaster university': 'mcmaster',
 'memorial': 'memorial',
 'memorial university': 'memorial',
 'montreal': 'montreal',
 'mount allison': 'mta',
 'mount allison university': 'mta',
 'mount royal': 'mru',
 'mount royal university': 'mru',
 'mount saint vincent': 'msvu',
 'mount saint vincent university': 'msvu',
 'mru': 'mru',
 'msvu': 'msvu',
 'mta': 'mta',
 'nipissing': 'nipissing',
 'nipissing university': 'nipissing',
 'northern british columbia': 'unbc',
 'ocad': 'ocad',
 'ocad university': 'ocad',
 'ontario college of art and design': 'ocad',
 'ontario tech': 'ontariotechu',
 'ontario tech university': 'ontariotechu',
 'ontariotechu': 'ontariotechu',
 'ottawa': 'ottawa',
 'polymtl': 'polymtl',
 'polytechnique': 'polymtl',
 'polytechnique montreal': 'polymtl',
 'polytechnique montréal': 'polymtl',
 "queen's": 'queens',
 "queen's university": 'queens',
 'queens': 'queens',
 'queens university': 'queens',
 'regina': 'regina',
 'rmc': 'rmc',
 'royal military college': 'rmc',
 'royal roads': 'rru',
 'royal roads university': 'rru',
 'rru': 'rru',
 'ryerson': 'tmu',
 'ryerson university': 'tmu',
 'saint francis xavier': 'stfx',
 'saint francis xavier university': 'stfx',
 "saint mary's": 'smu',
 "saint mary's university": 'smu',
 'sherbrooke': 'udes',
 'smu': 'smu',
 'st francis xavier': 'stfx',
 "st mary's": 'smu',
 'stfx': 'stfx',
 'sunnybrook': 'sunnybrook',
 'sunnybrook research institute': 'sunnybrook',
 'teluq': 'teluq',
 'thompson rivers': 'tru',
 'thompson rivers university': 'tru',
 'tmu': 'tmu',
 'toronto': 'toronto',
 'toronto metropolitan': 'tmu',
 'toronto metropolitan university': 'tmu',
 'trent': 'trent',
 'trent university': 'trent',
 'trinity western': 'twu',
 'trinity western university': 'twu',
 'tru': 'tru',
 'twu': 'twu',
 'téluq': 'teluq',
 'u of a': 'ualberta',
 'u of c': 'calgary',
 'u of m': 'manitoba',
 'u of o': 'ottawa',
 'u of t': 'toronto',
 'ualberta': 'ualberta',
 'ubc': 'ubc',
 'ucalgary': 'calgary',
 'udem': 'montreal',
 'udes': 'udes',
 'ulethbridge': 'lethbridge',
 'umanitoba': 'manitoba',
 'unbc': 'unbc',
 'universite de montreal': 'montreal',
 'universite de saint-boniface': 'USB',
 'universite de sherbrooke': 'udes',
 'universite du quebec a chicoutimi': 'uqac',
 'universite du quebec a montreal': 'uqam',
 'universite du quebec a rimouski': 'uqar',
 'universite du quebec a trois-rivieres': 'uqtr',
 'universite du quebec en abitibi-temiscamingue': 'uqat',
 'universite du quebec en outaouais': 'uqo',
 'universite laval': 'laval',
 'universite teluq': 'teluq',
 'university of alberta': 'ualberta',
 'university of british columbia': 'ubc',
 'university of calgary': 'calgary',
 'university of guelph': 'guelph',
 'university of lethbridge': 'lethbridge',
 'university of manitoba': 'manitoba',
 'university of montreal': 'montreal',
 'university of northern british columbia': 'unbc',
 'university of ottawa': 'ottawa',
 'university of regina': 'regina',
 'university of sherbrooke': 'udes',
 'university of toronto': 'toronto',
 'university of victoria': 'uvic',
 'university of waterloo': 'waterloo',
 'university of windsor': 'windsor',
 'university of winnipeg': 'uwinnipeg',
 'université de montréal': 'montreal',
 'université de saint-boniface': 'USB',
 'université de sherbrooke': 'udes',
 'université du québec en abitibi-témiscamingue': 'uqat',
 'université du québec en outaouais': 'uqo',
 'université du québec à chicoutimi': 'uqac',
 'université du québec à montréal': 'uqam',
 'université du québec à rimouski': 'uqar',
 'université du québec à trois-rivières': 'uqtr',
 'université laval': 'laval',
 'université téluq': 'teluq',
 'uoft': 'toronto',
 'uottawa': 'ottawa',
 'uqac': 'uqac',
 'uqam': 'uqam',
 'uqar': 'uqar',
 'uqat': 'uqat',
 'uqo': 'uqo',
 'uqtr': 'uqtr',
 'uregina': 'regina',
 'usb': 'USB',
 'ut': 'toronto',
 'uvic': 'uvic',
 'uwaterloo': 'waterloo',
 'uwindsor': 'windsor',
 'uwinnipeg': 'uwinnipeg',
 'uwo': 'western',
 'vancouver island': 'viu',
 'vancouver island university': 'viu',
 'victoria': 'uvic',
 'viu': 'viu',
 'waterloo': 'waterloo',
 'western': 'western',
 'western university': 'western',
 'wilfred laurier university': 'laurier',
 'wilfrid laurier': 'laurier',
 'wilfrid laurier university': 'laurier',
 'windsor': 'windsor',
 'winnipeg': 'uwinnipeg',
 'wlu': 'laurier',
 'york': 'york',
 'york university': 'york',
 'école de technologie supérieure': 'ets',
 "école nationale d'administration publique": 'enap'}

def normalize_institution(value: str | None) -> str | None:
    """Return a Borealis dataverse alias for a known institution name."""
    if not value:
        return None
    normalized = " ".join(value.strip().lower().split())
    return UNIVERSITY_DATAVERSE_MAP.get(normalized, value.strip())
